### ISSUE TITLE
Trying to generate manpage crashes Sphinx

### ISSUE THREAD

**Issue by tehe** [akheron/jansson#207]
Update: This happens on vanilla sources of 2.7 version.

When I tried generating manpage in the doc subdirectory, I'm having Sphinx crash on me. Yes, it looks like Sphinx bug (in fact I was able to work around that by hacking the manage writer in Sphinx) and I understand that I should eventually file the bug to Sphinx (as they instruct me below), but still thought that I'll let you know.

The crash is as follows:

```
$ sphinx-build -v -E -a -b man . _build/man3lib
Making output directory...
Running Sphinx v1.2.2
building [man]: all source files
updating environment: 8 added, 0 changed, 0 removed
reading sources... [ 12%] apiref
reading sources... [ 25%] changes
reading sources... [ 37%] conformance
reading sources... [ 50%] gettingstarted
reading sources... [ 62%] index
reading sources... [ 75%] portability
reading sources... [ 87%] tutorial
reading sources... [100%] upgrading

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... jansson.1 { gettingstarted upgrading tutorial conformance portability apiref changes }
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 208, in build
    self.builder.build_all()
  File "/usr/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 177, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.6/site-packages/sphinx/builders/manpage.py", line 89, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.6/site-packages/sphinx/writers/manpage.py", line 36, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python2.6/site-packages/docutils-0.12-py2.6.egg/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python2.6/site-packages/sphinx/writers/manpage.py", line 354, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: refcounting

Exception occurred:
  File "/usr/lib/python2.6/site-packages/sphinx/writers/manpage.py", line 354, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: refcounting
The full traceback has been saved in /tmp/sphinx-err-pFIPIm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

**Comment by akheron** [comment]
Fixed, and sorry it took so long.

**Comment by tehe** [comment]
Thanks for fixing this, much appreciated.
