### ISSUE TITLE
Valgrind libjansson invalid reads

### ISSUE THREAD

**Issue by sumitdvcloudx** [akheron/jansson#475]
Hi,

Valgrind has reported a few invalid reads in my application where the memory is both being allocated and accessed by libjansson. Can you please help with the cause?

Thanks.

==26271== Invalid read of size 4
==26271==    at 0x489597: hashlittle (in /opt/janus/bin/janus)
==26271==    by 0x48A2E9: hashtable_set (in /opt/janus/bin/janus)
==26271==    by 0x4875A1: json_object_set_new_nocheck (in /opt/janus/bin/janus)
==26271==    by 0x487D02: json_object_deep_copy (in /opt/janus/bin/janus)
==26271==    by 0x4892D9: json_deep_copy (in /opt/janus/bin/janus)
==26271==    by 0x471A4E: send_message_to_janus (vcx_session.c:796)
==26271==    by 0x4758BA: vcx_session_on_rx_message (vcx_session.c:391)
==26271==    by 0x476BB7: vcx_session_handler (vcx_session.c:168)
==26271==    by 0x5324FC4: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==26271==    by 0x6BEE183: start_thread (pthread_create.c:312)
==26271==    by 0x6F0203C: clone (clone.S:111)
==26271==  Address 0xd436204 is 52 bytes inside a block of size 55 alloc'd
==26271==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==26271==    by 0x4871E8: jsonp_malloc (in /opt/janus/bin/janus)
==26271==    by 0x48A39B: hashtable_set (in /opt/janus/bin/janus)
==26271==    by 0x4875A1: json_object_set_new_nocheck (in /opt/janus/bin/janus)
==26271==    by 0x487626: json_object_set_new (in /opt/janus/bin/janus)
==26271==    by 0x471885: send_message_to_janus (vcx_session.c:713)
==26271==    by 0x4758BA: vcx_session_on_rx_message (vcx_session.c:391)
==26271==    by 0x476BB7: vcx_session_handler (vcx_session.c:168)
==26271==    by 0x5324FC4: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==26271==    by 0x6BEE183: start_thread (pthread_create.c:312)
==26271==    by 0x6F0203C: clone (clone.S:111)

vcx_session.c:713 json_object_set_new(root, VCX_EVENT_MSG, json_string(str_msg));

**Comment by ploxiln** [comment]
Compiler optimizations have used a fancy technique to read 4 bytes at a time to find the null terminator byte, instead of checking byte-by-byte. It reads one byte past the requested size of the allocation, but in practice the allocation is rounded up to a power of two or a similarly round number. If you make sure jansson is compiled with `-O0` or `-O1` that will probably prevent this valgrind warning.

**Comment by sumitdvcloudx** [comment]
Thanks for the quick reply. The problem really is that the application is crashing with the following backtrace:

Thread 15 "vcx_ssn_thrd_ 2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde7fc700 (LWP 5709)]
0x00007ffff5ac47a7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff5ac47a7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5ac6ae0 in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004871d9 in jsonp_malloc ()
#3  0x000000000048724e in jsonp_strndup ()
#4  0x0000000000488748 in string_create ()
#5  0x0000000000488818 in json_stringn_nocheck ()
#6  0x00000000004888c6 in json_stringn ()
#7  0x000000000048887c in json_string ()
#8  0x0000000000471884 in send_message_to_janus (ssn=ssn@entry=0x7fffc40061c0, message=message@entry=0x7fffbc002cc0) at vcx/vcx_session.c:713
#9  0x00000000004758ab in vcx_session_on_rx_message (ssn=ssn@entry=0x7fffc40061c0, message=message@entry=0x7fffbc002cc0) at vcx/vcx_session.c:391
#10 0x0000000000476ba8 in vcx_session_handler (data=0x7fffc40061c0) at vcx/vcx_session.c:168
#11 0x00007ffff76bffc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff5e15184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007ffff5b4203d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by ploxiln** [comment]
if `malloc()` segfaulted, that is due to general memory corruption. It's not really possible to say what the root cause was. You're on the right path, using valgrind, but you have to get over some false-positives to get to the real cause.

**Comment by coreyfarrell** [comment]
I don't think an "invalid read" could cause this.  From what I've seen this is almost always caused by an "invalid write".  This could be due to a buffer-overrun, write after free, using a pointer to a stack variable after it was popped off the stack.  Generally when `malloc()` segfaults the backtrace does not tell you the cause of the corruption, it only tells you when the corruption was encountered.  I cannot rule out the possibility jansson has a bug but I will point out that jansson has [96% test coverage](https://coveralls.io/github/akheron/jansson) so I can say that the chances are low.

On rare occasion it could be due to faulty hardware (bad RAM or related hardware).  Some clues to this would be if you experience the memory error from multiple different applications or if your application fails on one piece of hardware but works fine on all others.
