### ISSUE TITLE
json_integer make coredump?

### ISSUE THREAD

**Issue by tesion99** [akheron/jansson#476]
Our program use jasson, but sometimes it makes coredump in function json_integer()
```
(gdb) 
#0  0x00007f8c14843154 in _int_malloc (av=av@entry=0x7f8bb0000020, bytes=bytes@entry=24) at malloc.c:3375
#1  0x00007f8c148461ac in __GI___libc_malloc (bytes=24) at malloc.c:2905
#2  0x00007f8c169c577e in json_integer (value=15) at value.c:796
#3  0x00007f8bd35f76ed in janus_pocroom_handler (data=<optimized out>) at plugins/janus_pocroom.c:4847
#4  0x00007f8c16c3d4f0 in g_thread_proxy (data=0x6ef990) at gthread.c:784
#5  0x00007f8c14b95dd5 in start_thread (arg=0x7f8bd29c7700) at pthread_create.c:307
#6  0x00007f8c148beead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
Does the malloc() makes this error???

**Comment by ploxiln** [comment]
This usually means there was general memory corruption - it does not provide useful clues as to the root cause.

(In general it is good to include a few more lines above, where it has the instruction address and signal which was the trigger for the coredump.)
