### ISSUE TITLE
json_object_set_new()  leads to core dump

### ISSUE THREAD

**Issue by sshsu** [akheron/jansson#482]
## description:
my jansson version is 2.12, here is my code in my server, when it runs to the last line to set field `responsecode`, it seldom triggers core dump
```
      int response_code = 200;
      json_t *response_msg = json_object();
      json_object_set_new(response_msg, "srtc", json_string("response"));
      json_object_set_new(response_msg, "responsetype", json_string("unsubscribe"));
      json_object_set_new(response_msg, "transaction", json_string(msg->transaction));
      json_t *response_body = json_object();
      json_object_set_new(response_body, "publisherid", json_string(publisher_name));
      json_object_set_new(response_msg, "body", response_msg);
  

      json_object_set_new(response_msg, "responsecode", json_integer(response_code));
```
backtrace as follow:
```
(gdb) bt
#0  hashtable_find_pair (hashtable=hashtable@entry=0x7fea9c057250, bucket=bucket@entry=0x7fea9c004a90, key=key@entry=0x7fead5daa857 "responsecode", hash=hash@entry=3175713256) at hashtable.c:93
#1  0x00007feaf1ef4549 in hashtable_set (hashtable=0x7fea9c057250, key=0x7fead5daa857 "responsecode", value=value@entry=0x7fea9c05e910) at hashtable.c:233
#2  0x00007feaf1ef9ce7 in json_object_set_new_nocheck (json=<optimized out>, key=<optimized out>, value=0x7fea9c05e910) at value.c:115
#3  0x00007fead5d8975c in janus_srtc_videoroom_handle_unsubscribe (handle=0x7feab0035b10, msg=0x7feaa4005380) at plugins/janus_srtc2_videoroom.c:3043
#4  0x00007fead5d9133b in janus_srtc_videoroom_message_handler (data=0x0) at plugins/janus_srtc2_videoroom.c:3747
#5  0x00007feaf216fc55 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007feaf0c9b6ba in start_thread (arg=0x7feacffff700) at pthread_create.c:333
#7  0x00007feaf09d141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
stack shows the problem happened in hashtable.c:93 ,  it is in the function hash_table_find_pair( )
```
80 static pair_t *hashtable_find_pair(hashtable_t *hashtable, bucket_t *bucket,
81                                   const char *key, size_t hash)
82{
83    list_t *list;
84    pair_t *pair;
85
86    if(bucket_is_empty(hashtable, bucket))
87        return NULL;
88
89    list = bucket->first;
90    while(1)
91    {
92        pair = list_to_pair(list);
93        if(pair->hash == hash && strcmp(pair->key, key) == 0)
94            return pair;
95
96        if(list == bucket->last)
97            break;
98
99        list = list->next;
100    }
101
102    return NULL;
103}
```
I found the value of `pair` in line 93 is `0x21` and value of `list` = `0x21` and value of `bucket->last` is `0x7fea9c000078` and value of `bucket->first` is `0x7fea9c017dc0`, then I check the value of `bucket->first->next` is `0x21`, as follow:
```
(gdb) p pair
$11 = (pair_t *) 0x21
(gdb) p list
$12 = (list_t *) 0x21
(gdb) p bucket->last 
$13 = (struct hashtable_list *) 0x7fea9c000078
(gdb) p bucket->first 
$14 = (struct hashtable_list *) 0x7fea9c017dc0
(gdb) p bucket->first->
next  prev  
(gdb) p bucket->first->next 
$15 = (struct hashtable_list *) 0x21
(gdb) p bucket->last->prev 
$16 = (struct hashtable_list *) 0x7fea9c065820
(gdb) p bucket->last->prev->prev 
$17 = (struct hashtable_list *) 0x75a456abfad13dcd
(gdb) p bucket->last->prev->prev->prev 
Cannot access memory at address 0x75a456abfad13dcd
```
so why the value of `list（bucket->first->next is 0x21)`turned to `0x21`？anything wrong?

**Comment by ploxiln** [comment]
adding object to itself:

```c
json_object_set_new(response_msg, "body", response_msg);
```

**Comment by sshsu** [comment]
thank you very much
